### ISSUE TITLE
number separator being both . and ,

### ISSUE THREAD

**Issue by iamcapote** [x3devships/delta-www#3]
website is displaying both "," and " . " as a decimal separator making it very confusing for some people. person who reported was in europe. example: displaying 200,000 delta and in the same page using 200.000 for the same number. best example in image[](url)
![screenshot](https://user-images.githubusercontent.com/23019072/235551293-0e9022a1-4ed9-4c3f-a394-79cfdaed1373.jpg)

**Comment by iamcapote** [comment]
hi friends i do not have any more information about this issue since it was reported to me, and the screenshot isnt mine. what i know: user was in computer somewhere in germany europe. as you can see the , and . are both being used to display decimal separators which can be confusing as they use the , in europe to separate the decimals. here is another screenshot from the same user using only , to separate decimals.

![image](https://user-images.githubusercontent.com/23019072/235774212-8933ab17-5451-4cff-9142-f2a62cba5430.png)

and another screenshot of a number using .

![image](https://user-images.githubusercontent.com/23019072/235774703-6d5bdffd-0d4d-4027-bbbc-a6df28157465.png)


user used delta.finance in what appears to be chrome. if i find more information ill let you know but thats as much as i know.

**Comment by notsegfault** [comment]
should be fixed and live
